### ISSUE TITLE
Deadlock 

### ISSUE THREAD

**Issue by egillax** [OHDSI/Apollo#1]
Hi @schuemie,

I tried running this on my data. But after 14 hours it hanged on partition 43 out of 50 with a deadlock. I ran with 50 partitions and 16 threads. I wasn't able to get a python stacktrace to see in which part it got stuck. 

Do you know what could be the issue? 

As as sidenote I see that it only took you 2 hours to process 2 million patients, my data is barely larger than that but took much more time. Could you share the settings you used?

**Comment by schuemie** [comment]
The settings I use are the default in the ini file: https://github.com/OHDSI/Apollo/blob/main/cehr_bert.ini

It seems indeed the code is getting stuck in some sort of loop on your data. Would you mind sending me the log file?

**Comment by egillax** [comment]
Here is the log.
[_cdm_processing_log.txt](https://github.com/OHDSI/Apollo/files/11598282/_cdm_processing_log.txt)

**Comment by egillax** [comment]
It's running, already 90 minutes in with just "starting partition 0 of 1" in the log. It could be there's something weird going on with our server in terms if io. I'm waiting for a good opportunity to restart it (it's being used by others).

**Comment by schuemie** [comment]
In profiling it will not got further than 'starting partition 0 of 1', which could still take as long as 4 hours judging by your log.

**Comment by schuemie** [comment]
If you're impatient could always add something like 
```python
if len(self._output) > 1000:
    return
```
here: https://github.com/OHDSI/Apollo/blob/main/cdm_processing/cehr_bert_cdm_processor.py#L151

**Comment by schuemie** [comment]
Thanks! That actually looks totally fine. For reference, here's the same output for my data. It seems there are twice as many event - visit combinations to evaluate in your data, meaning it takes twice as long. That does make me realize there's a non-linearity here: if a person has *lots* of events and visits, processing time would be extremely long. I'll put together some code to explore this.
```
         242040557 function calls (238646433 primitive calls) in 257.625 seconds

   Ordered by: cumulative time
   List reduced from 1156 to 25 due to restriction <25>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      6/1    0.000    0.000  257.625  257.625 {built-in method builtins.exec}
        1    0.018    0.018  257.625  257.625 abstract_cdm_processor.py:75(process_cdm_data)
        1    0.646    0.646  253.429  253.429 abstract_cdm_processor.py:102(_process_partition)
    10000    0.078    0.000  239.397    0.024 cehr_bert_cdm_processor.py:150(_process_person)
      919    0.217    0.000  236.587    0.257 cdm_processor_utils.py:72(call_per_observation_period)
     1131    4.708    0.004  226.719    0.200 cehr_bert_cdm_processor.py:161(_process_observation_period)
     1131    0.637    0.001   98.228    0.087 cdm_processor_utils.py:215(group_by_visit)
528781/299431    1.926    0.000   67.091    0.000 indexing.py:1089(__getitem__)
     1129    4.700    0.004   59.540    0.053 cdm_processor_utils.py:278(<listcomp>)
   229350    0.753    0.000   48.341    0.000 indexing.py:1277(_getitem_tuple)
   229350    1.968    0.000   46.770    0.000 indexing.py:967(_getitem_lowerdim)
  1254601    6.326    0.000   43.180    0.000 frame.py:3713(__getitem__)
   458700    1.922    0.000   40.480    0.000 indexing.py:1309(_getitem_axis)
   137900    0.328    0.000   39.485    0.000 series.py:4516(apply)
   137900    0.383    0.000   38.528    0.000 apply.py:1010(apply)
    68950    0.939    0.000   38.200    0.001 cdm_processor_utils.py:127(union_domain_tables)
1088717/1088631    5.306    0.000   37.486    0.000 series.py:368(__init__)
   233388    1.275    0.000   34.643    0.000 generic.py:6161(astype)
    95488    1.478    0.000   30.781    0.000 apply.py:1061(apply_standard)
   462819    2.107    0.000   30.117    0.000 frame.py:3639(_ixs)
   229350    0.648    0.000   28.628    0.000 indexing.py:1117(_getbool_axis)
   253145    0.949    0.000   27.029    0.000 frame.py:641(__init__)
    70328    0.714    0.000   23.565    0.000 construction.py:411(dict_to_mgr)
  1240824    2.606    0.000   23.512    0.000 frame.py:4253(_get_item_cache)
   233388    0.688    0.000   21.629    0.000 managers.py:442(astype)
```

**Comment by schuemie** [comment]
I just pushed some changes to [GeneralPretrainedModelTools](https://github.com/OHDSI/GeneralPretrainedModelTools). Would you mind installing the latest version, and run the `GeneralPretrainedModelTools::computeParquetDescriptives()` function? It would be interesting to see the distribution of the number of records per person. Below are my stats. I already see some things I need to investigate (persons with > 10,000 procedures?)

cdmTableName | rowCount | personCount | meanRecordsPerPerson | minRecordsPerPerson | p5RecordsPerPerson | p25RecordsPerPerson | medianRecordsPerPerson | p75RecordsPerPerson | p95RecordsPerPerson | maxRecordsPerPerson
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
person | 2000000 | 2000000 | 1.0 | 1 | 1.0 | 1.0 | 1 | 1.0 | 1.0 | 1
observation_period | 2251693 | 2000000 | 1.1 | 1 | 1.0 | 1.0 | 1 | 1.0 | 2.0 | 18
visit_occurrence | 71881775 | 1705138 | 42.2 | 1 | 1.0 | 5.0 | 16 | 46.1 | 169.8 | 2937
condition_occurrence | 87060916 | 1588216 | 54.8 | 1 | 1.0 | 5.9 | 18 | 54.9 | 223.6 | 11892
drug_exposure | 61539714 | 1542649 | 39.9 | 1 | 1.0 | 4.3 | 13 | 38.9 | 167.0 | 3620
procedure_occurrence | 101190010 | 1634165 | 61.9 | 1 | 1.5 | 7.2 | 22 | 63.0 | 250.1 | 10236
device_exposure | 3909077 | 488938 | 8.0 | 1 | 1.0 | 1.0 | 2 | 6.0 | 32.2 | 2509
measurement | 45460377 | 1335253 | 34.0 | 1 | 1.0 | 4.6 | 13 | 34.4 | 132.1 | 9510
observation | 90684276 | 2000000 | 45.3 | 1 | 2.0 | 11.6 | 26 | 57.2 | 154.2 | 2999
death | 2924 | 2924 | 1.0 | 1 | 1.0 | 1.0 | 1 | 1.0 | 1.0 | 1
concept | 3534176 | NA | NA | NA | NA | NA | NA | NA | NA | NA
concept_ancestor | 32308827 | NA | NA | NA | NA | NA | NA | NA | NA | NA

**Comment by schuemie** [comment]
I just pushed a bunch of changes, including the use of dictionaries for mapping events to visits. This should make performance scale more linearly with the number of events and visits per person. 

It would still be good to use `GeneralPretrainedModelTools::computeParquetDescriptives()` to see if there are extremes that should be removed from the data altogether.

(I also fixed the profiling code. Sorry for that)

**Comment by egillax** [comment]
Here's the table stats for my data:


cdmTableName | rowCount | personCount | meanRecordsPerPerson | minRecordsPerPerson | p5RecordsPerPerson | p25RecordsPerPerson | medianRecordsPerPerson | p75RecordsPerPerson | p95RecordsPerPerson | maxRecordsPerPerson
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
person | 2674547 | 2674547 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1
observation_period | 2674547 | 2674547 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1
visit_occurrence | 149438034 | 2620220 | 57.0326285579074 | 1 | 2.98038849985218 | 12.7625633759532 | 30.7669669707209 | 69.1722298759398 | 198.744428693358 | 14670
condition_occurrence | 205039679 | 2642492 | 77.5933017015756 | 1 | 5.22234466956398 | 19.5790973551925 | 41.1455909860662 | 84.2125008969059 | 272.627566780442 | 12130
drug_exposure | 325462623 | 2571292 | 126.575520399861 | 1 | 2.05215991353836 | 12.4970085613701 | 38.9704572642837 | 122.659193879923 | 500.122222578228 | 31924
procedure_occurrence | 28739598 | 1949175 | 14.7444934395321 | 1 | 1 | 3 | 7.34718333748178 | 17.0902203367207 | 52.5269393213077 | 1733
device_exposure | 13266407 | 1256272 | 10.5601390463212 | 1 | 1 | 1 | 2.97381788951481 | 7.30553179703874 | 42.1551378474326 | 2262
measurement | 281813870 | 2361343 | 119.344741530561 | 1 | 1.41682953694791 | 12.6299376659684 | 46.0796003555168 | 142.064847201424 | 502.52088550339 | 22507
observation | 114786969 | 2166697 | 52.9778593868917 | 1 | 1 | 3.97109443791463 | 11.6304541787594 | 36.2849748741652 | 264.555745534596 | 15434
death | 101045 | 101045 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1

Looks like in general I have more records per patients, especially for ```drug_exposures```.  I also have some of these extreme outliers. 

The new code did finish in 667 seconds instead of 755 for the 1000 patients.

But for reference the code from the `cehr-bert` repo finishes in about 30 minutes. I know there are some differences in what the codes do, related to the observational period and maybe more. I would still hope to be able to run `Apollo` in something less than 14+ hours. 

One thing I did notice is within each partition there is a for loop going over all patients within the partition and processing them one by one in series. Did you consider vectorizing that? Either processing all patients within partition at once, or in batches so the memory doesn't grow to much per process.  I'm not sure though how the code lends itself to that.

One other thing, since I'm pretty sure when I ran the code originally it hit a [deadlock](https://en.wikipedia.org/wiki/Deadlock), i.e. it stopped and the cpu wasn't doing anything. I think it could be related to the default backend for the multiprocessing pool on linux. Seems the `fork` backend can get stuck or crash. More about it [here](https://pythonspeed.com/articles/python-multiprocessing/). My suggestion would be to hardcode `spawn` as the backend, which is already the default on windows and mac.

I'll run `Apollo` now overnight with `spawn` and see how it goes.

**Comment by egillax** [comment]
Everything ran successfully in about 12 hours. Only thing I changed from the current `main` was initialize the `pool` with:

```python
pool = multiprocessing.get_context('spawn').Pool(processes=self._max_cores)
```

I'll check the output now and compare it to that from the `cehr-bert` repo

**Comment by schuemie** [comment]
Thanks! 'spawn' is the default on Windows and MacOS. Are you running Linux?

**Comment by schuemie** [comment]
Sorry, missed your earlier post. You're running Linux.

The processing of one patient at a time was deliberate, to make the code more intuitive, so we can easily adapt it to different approaches. But of course execution time should ideally still be in the same ballpark as the original code. Are the 12 hours and 30 minutes you mentioned for the same set of patients?

The extremes are concerning though. There's at least one patient with 14,670 visits, and since I don't think visits are allow to overlap on a day, that would mean at least 40 years of non-stop consecutive visits!

**Comment by schuemie** [comment]
Ok, there can be multiple visits on a day: 
> Visits can be adjacent to each other, i.e. the end date of one can be identical with the start date of the other. As a consequence, more than one-day Visits or their descendants can be recorded for the same day. Multi-day visits must not overlap, i.e. share days other than start and end days.

https://ohdsi.github.io/CommonDataModel/cdm54.html#VISIT_OCCURRENCE

**Comment by egillax** [comment]
>The extremes are concerning though. There's at least one patient with 14,670 visits, and since I don't think visits are allow to overlap on a day, that would mean at least 40 years of non-stop consecutive visits!

I did check out this individual. He indeed had multiple visits registered per day, but almost none of them had any actual clinical events connected to them. Looking at his data after processing in Apollo there are 262 visits remaining.

>The processing of one patient at a time was deliberate, to make the code more intuitive, so we can easily adapt it to different approaches. But of course execution time should ideally still be in the same ballpark as the original code. Are the 12 hours and 30 minutes you mentioned for the same set of patients?

Yes same set of patients. Not necessarily same computer resources though, Apollo used 16 cores and about 24GB of RAM. Spark used 30 cores and I didn't notice the memory, so that affects these numbers.  I agree it would be ideal if we would be in the same ballpark as the original.

**Comment by schuemie** [comment]
I'm surprised by the 24GB of RAM. The script should basically have the data for 1 patient in memory at a time, which should measure in MB, not GB. When processing CCAE, it stays around 300MB per thread. 

The Apollo script also adds more tables, including the measurement and observation table, so that is also a difference.

If you wouldn't mind. Could you try running with more partitions? You'd have to download the data again for that. I'm using 200 partitions.

**Comment by schuemie** [comment]
Thanks for giving that a try. The arrow implementation is more memory-hungry per thread, but you'll need fewer parallel threads (arrow also launches threads of its own).
