### ISSUE TITLE
unique concept_ids occurring on same day

### ISSUE THREAD

**Issue by egillax** [OHDSI/Apollo#2]
I notice one difference between Apollo and the original implementation. 

In the original if the same event was recorded twice or more on the same day it was merged to one event. Apollo does not do this. In my data at least this seems to happen sometimes. 

Should we also merge these events in Apollo? These duplicate events are not adding any information to the data and every space in the patient sequence is precious since transformers scale polynomially with sequence length

**Comment by schuemie** [comment]
Yes, removing duplicates makes sense. I implemented it in [this branch](https://github.com/OHDSI/Apollo/tree/remove_duplicate_concepts/). Unfortunately, it does add quite some compute (about 30%).

I'm exploring if we can use pure arrow to implement the same behavior. I would just like to get rid of the Spark dependency, which I think will make our life harder (especially when we want to use reticulate).

**Comment by schuemie** [comment]
This has been implemented
