### ISSUE TITLE
enforce same type of schema

### ISSUE THREAD

**Issue by egillax** [OHDSI/Apollo#4]
I just ran the new code. It's very fast, faster than the spark version on my server.

I ran into a minor issue though. Arrow does some automatic casting. Which resulted in this table concat [here](https://github.com/OHDSI/Apollo/blob/main/cdm_processing/cdm_processor_utils.py#L111) to fail because of different schema between tables. The `concept_id` was `double` in my clinical event tables while it's hardcoded to be `int64` for the `death` table. I fixed it by adding a `.cast(death.schema)` after the `rename_columns` [here](https://github.com/OHDSI/Apollo/blob/main/cdm_processing/cdm_processor_utils.py#L109). 

Maybe a better way would be to provide a schema when downloading the data from the database so arrow doesn't try to automatically determine the datatype?

**Comment by schuemie** [comment]
Sorry, didn't see this issue until now. 

I agree it would be best to fix this when downloading. The downloading is done [here](https://github.com/OHDSI/GeneralPretrainedModelTools/blob/main/R/DataExtraction.R#L324). BIGINT fields will be cast to integer64 in R, but not all database platforms support BIGINT. Which database platform are you using?

I'll add code to force the various data types after download to GeneralPretrainedModelTools.

**Comment by egillax** [comment]
I'm using postgres. The `concept_ids` are stored as `integer` in the database.

**Comment by schuemie** [comment]
Ah, that's right. Concept IDs are supposed to be 32-bit integers. Other IDs, such as person IDs, are also defined as 32-bit bit integers in the official CDM documentation, but for many databases that is not sufficient, and they unofficially use 64-bits instead. I'll modify GeneralPretrainedModelTools to force concept IDs to 32-bit ints, and all other ints to 64 bits. I'll also modify the Apollo code so Death uses a 32-bit int for the concept ID.
